# Used for creating a concourse service account

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1alpha1
metadata:
  name: concourse-ci-rbac

# subjects holds references to the objects the role applies to.
subjects:
 # May be "User", "Group" or "ServiceAccount".
  - kind: ServiceAccount
    name: concourse-ci
    namespace: default

# roleRef contains information about the role being used.
# It can only reference a ClusterRole in the global namespace.
roleRef:
  kind: ClusterRole
  name: admin
  apiVersion: rbac.authorization.k8s.io/v1alpha1
